
CREATE TABLE "ETL"."CRIME_LACITY" 
   (	"DR_NO" NUMBER(15,0) NOT NULL ENABLE, 
	"DATE_RPDT" VARCHAR2(30), 
	"AREA_NAME" VARCHAR2(29), 
	"CM_CD_DESC" VARCHAR2(60)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

 SELECT AREA_NAME FROM "ETL"."CRIME_LACITY_13"  GROUP BY AREA_NAME ;
 SELECT AREA_NAME FROM "ETL"."CRIME_LACITY_21"  GROUP BY AREA_NAME ;
 
 SELECT *
FROM "ETL"."CRIME_LACITY_21"
ORDER BY "DR_NO" DESC
FETCH FIRST 50 ROWS ONLY;
  
  
  
 
  SELECT * FROM "ETL"."CRIME_LACITY_21" ;
  
  TRUNCATE TABLE "ETL"."CRIME_LACITY_21" ;